### PR TITLE
Fix bug with Streaming#thunk.

### LINKED ISSUE #677: Streaming.thunk doesn't seem to reevaluate thunk
The ScalaDoc for `Streaming.thunk` says that the thunk may not be pure. However, it doesn't seem to support this use-case. In the following example, I would expect the output to be `List(1, 2, 3, 4)`, but it is `List(1, 1, 1, 1)`.

```scala
scala> var i = 0
i: Int = 0

scala> Streaming.thunk{() => i += 1; i}.take(4).toList
res6: List[Int] = List(1, 1, 1, 1)
```

Here is a test that helped me catch this:

```scala

  test("thunk is evaluated for each item") {
    // don't want the stream to be too big
    implicit val arbInt = Arbitrary(Gen.choose(-10, 20))
    forAll { (start: Int, end: Int) =>
      var i = start - 1
      val stream = Streaming.thunk{ () => i += 1; i}.takeWhile(_ <= end)
      stream.toList should === ((start to end).toList)
    }
  }
```

### PR DESCRIPTION
**Pull request by non**
The .thunk method is not supposed to memoize the results,
allowing the caller to provide an impure function which
returns different values on different calls.

However, .thunk's definition used .knot with memoization,
which completely defeated the point. This commit removes
the memoization allowing this method to function correctly.

Fixes #677.

### CODE REVIEW

File: core/src/main/scala/cats/data/Streaming.scala [hunk 1]
```diff
@@ -812,7 +812,7 @@ object Streaming extends StreamingInstances {
    * traversals produce the same results.
```
Comment (ceedubs) [inline core/src/main/scala/cats/data/Streaming.scala]: I think this doc needs to be updated to no longer say that the result is memoized.

**Comment by ceedubs** [comment]
:+1:

**Comment by adelbertc** [comment]
:+1:
